spring:
  application:
    name: task-management
  threads:
    virtual:
      enabled: true

  r2dbc:
    url: ${POSTGRES_URL:r2dbc:postgresql://localhost:5432/task-mgmt}
    #    url: r2dbc:postgresql://taskmgmt-db:5432/task-mgmt
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:hendi34}
  #    initialization-mode: never
  #    schema: update

  sql:
    init:
      schema-locations: classpath:schemas.sql
      mode: ALWAYS

#logging:
#  level:
#    org.springframework: DEBUG
#  datasource:
#    url: jdbc:postgresql://taskmgmt-db:5432
#    name: task-mgmt
#    username: postgres
#    password: 123456
#    driver-class-name: org.postgresql.Driver
